Meteor.methods({
    removeStaff(id){
        Collection.Staff.remove(id);
    },
    removeCustomer(id){
        Collection.Customer.remove(id);
    },
    removeOrderItem(id){
        Collection.Item.remove(id);
    },
    removeJournalItem(id){
        Collection.JournalItem.remove(id);
    }
});